# Generated by Django 6.0.4 on 2026-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='notes',
        ),
        migrations.AddField(
            model_name='checkin',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
