# Generated by Django 6.0.4 on 2026-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_checkin_notes_checkin_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='reminder_time',
        ),
    ]
